project:
  type: book
  output-dir: web

#lang: pt-BR # NOTE: This gives the error: https://github.com/Ar-Kan/meu-calculo-numerico/actions/runs/12527126226
language: helpers/custom.yml
strip-comments: true
bibliography: referencias.bib
date: last-modified
date-format: D/MM/YYYY
filters:
  - helpers/mathpunctuation.lua

crossref:
  chapters: true
  fig-prefix: ""
  eq-prefix: ""
  sec-prefix: ""
  def-prefix: ""
  tbl-prefix: ""

book:
  title: Meu Cálculo Numérico
  subtitle: Um livro colaborativo
  date: today
  date-format: D/MM/YYYY
  author:
    - Arquimedes Macedo
    - REAMAT
  cover-image: jumbotron.jpg
  repo-url: https://github.com/Ar-Kan/meu-calculo-numerico
  site-url: https://ar-kan.github.io/meu-calculo-numerico/
  repo-branch: master
  repo-actions:
    - edit
    - issue
  sharing:
    - twitter
    - facebook
    - linkedin
  downloads: pdf
  open-graph: true
  reader-mode: true
  sidebar:
    title: 'Meu Cálculo Numérico <br> <span style="color: gray; font-size: 0.8rem;">{{< meta date >}}</span> <br> [<span style="color: gray; font-size: 0.7rem; text-decoration: underline;">CC-BY-SA 3.0</span>](https://creativecommons.org/licenses/by-sa/3.0/deed.pt_BR)<br>'
    align: left
  page-footer:
    left: |
      <a href="https://www.ufrgs.br/reamat/CalculoNumerico/index.html">REAMAT</a>
    right: |
      Este livro foi criado com <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - prefacio.qmd
    - introducao.qmd
    - part: capitulos/01_aritmetica/00_capitulo.qmd
      chapters:
        - capitulos/01_aritmetica/01_sistema_de_numeracao.qmd
  appendices:
    - apendices/a1-python.qmd

format:
  html:
    cover-image: jumbotron.jpg
    favicon: favicon.ico
    email-obfuscation: references
    code-link: true
    link-external-icon: false
    link-external-newwindow: true
    number-sections: true
    toc: true
    collapse: true
    html-math-method:
      method: mathjax
      url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
    include-in-header: helpers/html/header-includes.html
    reference-location: margin
    citation-location: margin
    toc-location: right
    toc-expand: true
    theme:
      light:
        - flatly
        - helpers/html/styles.scss
        - helpers/html/light.scss
      dark:
        - darkly
        - helpers/html/styles.scss
        - helpers/html/dark.scss
    fig-width: 5
    fig-height: 5
    fig-align: center

  pdf:
    keep-tex: false
    pdf-engine: lualatex
    title: Meu Cálculo Numérico
    subtitle: Um livro colaborativo
    documentclass: book
    geometry:
      - paperwidth=8.00in
      - paperheight=10.00in
      - left=1.25in
      - textwidth= 5.25in
      - top=1.00in
      - textheight=8.25in
      #- showframe # For debugging
    toc: true
    colorlinks: true
    fig-width: 5
    fig-height: 5
    fig-align: center
