on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

name: render

jobs:
  render:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      isExtPR: ${{ github.event.pull_request.head.repo.fork == true }}
    steps:
      - name: Configure Git user
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.56

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render book
        run: quarto render

      - name: Deploy to GitHub Pages
        if: contains(env.isExtPR, 'false')
        id: gh-pages-deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: web
